# Generated by Django 4.2.7 on 2023-11-19 14:38

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_created_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='url_imagem',
            field=models.ImageField(null=True, upload_to=core.models.user_image_field),
        ),
    ]
