# Generated by Django 4.2.7 on 2023-11-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_locked_at_user_login_attempts_user_unlocked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
