# Generated by Django 4.2.7 on 2023-11-19 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='conta',
            name='saldo',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
