# Generated by Django 4.2.7 on 2023-11-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_transfer_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
