# Generated by Django 4.2.7 on 2023-11-27 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_transfer_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='url_imagem',
            new_name='url_image',
        ),
    ]
