# Generated by Django 4.2.7 on 2023-11-27 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_url_imagem_user_url_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanInstallments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payed_date', models.DateTimeField(null=True)),
                ('due_date', models.DateTimeField()),
                ('loanId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.loan')),
            ],
        ),
    ]
