# Generated by Django 4.2.7 on 2023-11-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_loan_status_loan_payed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
