# Generated by Django 4.2.7 on 2023-11-24 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_account_loan_alter_transfer_receiver_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='user',
            new_name='account',
        ),
    ]
