# Generated by Django 4.2.7 on 2023-11-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_transfer_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='fees',
            field=models.DecimalField(decimal_places=3, default=0.025, max_digits=5),
        ),
    ]
