# Generated by Django 4.2.7 on 2023-11-24 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_user_loan_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='fee',
            new_name='fees',
        ),
    ]
