# Generated by Django 4.2.7 on 2023-11-29 19:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_loan_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installments', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('payed', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.account')),
            ],
        ),
        migrations.AlterField(
            model_name='loan',
            name='fees',
            field=models.DecimalField(decimal_places=3, default=1.025, max_digits=5),
        ),
        migrations.CreateModel(
            name='CreditInstallments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payed_date', models.DateTimeField(null=True)),
                ('due_date', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creditId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.credit')),
            ],
        ),
    ]
