# Generated by Django 4.2.7 on 2023-11-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_fee_loan_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='nickname',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
