# Generated by Django 4.2.7 on 2023-11-24 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_account_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='nickname',
        ),
    ]
